const interests = [
    'Artificial Intelligence',
    'Distributed Computing',
    'Computer Vision',
    'Natural Language Processing',
    'Machine Learning',
    'Data Science',
    'Big Data',
    'Cloud Computing',
    'Blockchain',
    'Internet of Things',
    'Cybersecurity',
    'Mobile App Development',
    'Web Development',
    'Game Development',
    'Virtual Reality',
    'Augmented Reality',
    'Data Visualization',
    'Database Management',
    'Computer Networks',
    'Operating Systems',
    'Software Engineering',
    'Algorithms and Data Structures',
    'Computer Graphics',
    'Parallel Computing',
    'Quantum Computing',
    'Robotics',
    'Human-Computer Interaction',
    'Ethical Hacking',
    'DevOps',
    'Compiler Design',
    'Embedded Systems',
    'Natural Language Understanding',
    'Speech Recognition',
    'Image Processing',
    'Deep Learning',
    'Reinforcement Learning',
    'Computer Architecture',
    'Information Retrieval',
    'Data Mining',
    'Cloud Architecture',
    'Cryptography',
    'Mobile Game Development',
    'Frontend Development',
    'Backend Development',
    'Full Stack Development',
    'API Development',
    'Serverless Computing',
    'Microservices',
    'Containerization',
    'Data Analytics',
    'Business Intelligence',
    'Predictive Analytics',
    'Computer Security',
    'Wireless Networks',
    'Data Warehousing',
    'Geographic Information Systems',
    'E-commerce Development',
    'UI/UX Design',
    'Web Accessibility',
    'Parallel Algorithms',
    'Concurrency',
    'Computer Vision Applications',
    'Information Security',
    'Network Security',
    'Mobile Security',
    'Software Testing',
    'Code Optimization',
    'Artificial Neural Networks',
    'Cloud Security',
    'Digital Signal Processing',
    'Natural Language Generation',
    'Internet Security',
    'Backend as a Service',
    'Internet Routing',
    'Virtual Machines',
    'Computer Forensics',
    'Real-Time Systems',
    'Operating System Design',
    'Human-Robot Interaction',
    'Biometrics',
    'Internet Privacy',
    'Cryptocurrency',
    'Chatbot Development',
    'Geometric Modeling',
    'Machine Vision',
    'High-Performance Computing',
    'Data Privacy',
    'Data Engineering',
    'Network Programming',
    'Data Governance',
    'Secure Coding',
    'Game Design',
    'Computer-Aided Design',
    'Data Compression',
    'Network Analysis',
    'Cloud Storage',
    'Software Project Management',
    'Agile Development',
    'Information Theory',
    'Data Structures',
];

export default interests;